<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ClearSkies.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ClearSkies.Engine\ClearSkies.Engine.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LiteNetLib" Version="2.1.4" />
  </ItemGroup>

</Project>
